### ISSUE TITLE
Vendor email alert - auction delivery has been rejected

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1018]
As an admin, I want to be consistent about notifications to vendors whose work I have rejected and I want to do this automatically so I don't have to remember to do it, so the system should send an automated email letting the vendor know that their work was rejected

- [x] **Scenario: System sends automated notification to winning vendor that work was rejected**
- Given that an auction exists
- And the winning vendor has delivered code (clicked the "I'm Done" button)
- And the vendor has an email address
- When an admin rejects the work (clicks "Reject" on the show page, or sets the delivery status to "Rejected" on the auction edit form)
- Then an email is sent to the the vendor's email with this content

``` yaml
subject: "18F Micro-purchase Auction Status"
para_1: "We regret to inform you that your work for %{auction_title} was rejected
         on mm/dd/yyyy. For more information please see the auction details here  
         %{auction_url} or contact us at micropurchase@gsa.gov. Though this auction 
         did not work out, we hope you will continue to participate in the future."
sign_off: "Sincerely,"
from: "The 18F Micro-purchase team"
        
```
