### ISSUE TITLE
Vendor email alert - auction delivery accepted

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1019]
As an admin, I want to be consistent about notifications to vendors whose work I accepted and I want to do this automatically so I don't have to remember to do it, so the system should send an automated email letting the vendor know that their work was accepted

- [x] **Scenario: System sends automated notification of acceptance to winning vendor WITH payment URL**
- Given that an auction exists
- And the winning vendor has delivered code (clicked the "I'm Done" button)
- And the vendor has an email address
- And the vendor has specified a payment URL
- When an admin accepts the work (clicks "Accept" on the show page, or sets the result to "Accepted" on the auction edit form)
- Then an email is sent to the the vendor's email with this content

``` yaml
subject: "18F Micro-purchase Auction Status"
para_1: "Congratulations! The work you submitted for %{auction_title} was accepted
         on %{auction_acceptance_date}! Payment in the amount of %{auction_winning_bid} 
         will be issued to %{vendor_payment_url} as specified in your profile."
para_2: Again, great job! We look forward to working with you again in the future."
```

- [x] **Scenario: System sends automated notification of acceptance to winning vendor WITHOUT payment URL**
- Given that an auction exists
- And the winning vendor has delivered code (clicked the "I'm Done" button)
- And the vendor has an email address
- And the vendor has NOT specified a payment URL
- When an admin accepts the work (clicks "Accept" on the show page, or sets the result to "Accepted" on the auction edit form)
- Then an email is sent to the the vendor's email with this content

``` yaml
subject: "18F Micro-purchase Auction Status"
para_1: "Congratulations! The work you submitted for %{auction_title} was accepted
         on %{auction_acceptance_date} ! To ensure prompt payment in the amount of 
         %{auction_winning_bid} please add a payment URL to your profile on the 
         micro-purchase platform." 
para_2: Again, great job! We look forward to working with you again in the future."
```

- And "add a payment URL to your profile" should link to that vendor's profile
